# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0c6a167d34d0aec6d5a2fb98c8f34da0650d972af11c582a3a09834910c4dff491a0ffa814025968417f6938d85396d1d8598292378682f4e07bb548c8f48dd6

test:
  secret_key_base: e327a41f2bb3d8e8c29a15f8a715d0eab37fcee2e3300fff2ba02d7c2d5c2a757d31ed7ceb3b64046b7a7045b58dfe1fcca090fc39f3ca51b92e70fd65b0c0d4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
